framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    default_locale: fr
    session: true

    trusted_proxies: '127.0.0.1'
    trusted_headers:
        - x-forwarded-for
        - x-forwarded-host
        - x-forwarded-proto
        - x-forwarded-port

    translator:
        default_path: '%kernel.project_dir%/translations'

    router:
        utf8: true
